# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'erb'
require File.join(File.dirname(__FILE__), '..', 'vagrant', 'utils')

if provisioning?
  check_kubernetes
  check_packages PACKAGES
  check_images IMAGES
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  PACKAGES.each do |package|
    config.vm.provision :file, source: kubernetes_path("bazel-bin/build/debs/#{package}.deb"), destination: kubernetes_target_path("#{package}.deb")
  end

  IMAGES.each do |image|
    config.vm.provision :file, source: kubernetes_path("bazel-bin/build/#{image}.tar"), destination: kubernetes_target_path("#{image}.tar")
  end

  custom_container_images.each do |image_path|
    config.vm.provision :file, source: image_path, destination: custom_container_image_target_path(image_path)
  end

  custom_manifests.each do |manifest_path|
    config.vm.provision :file, source: manifest_path, destination: custom_manifests_target_path(manifest_path)
  end

  config.vm.provision :shell, inline: template("scripts/install.erb", binding)
end
