# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'erb'
require File.join(File.dirname(__FILE__), '..', 'vagrant', 'utils')

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end

  PACKAGES.each do |package|
    config.vm.provision :file, source: kubernetes_path("bazel-bin/build/debs/#{package}.deb"), destination: kubernetes_target_path("#{package}.deb")
  end

  IMAGES.each do |image|
    config.vm.provision :file, source: kubernetes_path("_output/release-images/amd64/#{image}.tar"), destination: kubernetes_target_path("#{image}.tar")
  end

  config.vm.provision :shell, inline: template("scripts/install.erb", binding)
end
